import Head from 'next/head'
import SidebarComponent from '../components/SidebarComponent'

export default function Home() {
  return (
    <div className='flex flex-col h-screen'>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SidebarComponent />
    </div>
  )
}
