import React from 'react'
import Head from 'next/head'
import {auth, provider} from '../firebase';

const Login = () => {

    const signIn = () => {
        auth.signInWithPopup(provider).catch(alert)
    }

    return (
        <div>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-full h-screen bg-gray-100 flex items-center justify-center'>
                <div className='p-6 bg-wgite w-full bg-white flex my-auto py-28 max-w-lg rounded-md shadow-lg'>
                    <div className='w-full h-auto flex flex-col'>
                        <img 
                            className='mx-auto w-48'
                            src='/whatsapp-icon-seeklogo.com.svg'
                        />
                        <button onClick={signIn} className='w-3/5 uppercase mx-auto mt-8 shadow-md border-2 focus:outline-none active:shadow-none rounded-md p-2'>Sign in with google</button>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Login
