import React from 'react'
import Head from 'next/head'
import HeaderComponent from '../components/HeaderComponent';

const Search = () => {
    return (
        <div>
            <Head>
                <title>Search Results</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderComponent />
        </div>
    )
}

export default Search
